version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/python:latest'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: pip install -r requirements/dev.txt
      - run: python -m pytest
